# Generated by Django 5.1.7 on 2025-03-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='file_id',
            field=models.CharField(max_length=255),
        ),
    ]
